### ISSUE TITLE
Hover image is not circle

### ISSUE THREAD

**Issue by asifrpatel** [xenione/loupe#2]
When touch on image there is square image hovering and inside square is white circle. I is not cropped in circle.

**Comment by xenione** [comment]
I don't understand what you are saying. Could you attach a screenshoot?

**Comment by asifrpatel** [comment]
![screen shot 2017-03-08 at 1 57 27 pm](https://cloud.githubusercontent.com/assets/13833229/23719163/40d28fae-0408-11e7-9ce7-27e56390dae1.png)

**Comment by xenione** [comment]
Issue fixed. No library fixed release. as a walkaround you can do that:
 if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR2) {
            mLoupeView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
 }
basically disable hardware accelerated if version below 18, since no support clipPath on canvas.
